export * from './BlurText'
export * from './Footer'
export * from './LandingPageBg'
export * from './TypingText'
export * from './Screen1'
export * from './Screen2'
export * from './LandingPageBg'
export * from './MagicCard'